# -*- coding: utf-8 -*-
import json

# 200 enrichments in the SAME order as phr_batch_todo.json (index 0..199).
# Each tuple: (en2, cn2, note)
enrich = [
    ("She is used to eating spicy food.", "她习惯吃辣的食物。", "后接名词/动名词，不接不定式。"),
    ("A few games helped break the ice among strangers.", "几个小游戏有助于陌生人之间打破僵局。", "多用于社交/会议开场缓解尴尬。"),
    ("He is by no means a qualified teacher.", "他绝不是一个合格的老师。", "置系动词后或句首表强调否定。"),
    ("Do you get along with your new roommate?", "你和新室友相处得好吗？", "常与 well/badly 连用表相处状态。"),
    ("Who is in charge of the kitchen tonight?", "今晚谁负责厨房？", "表“掌管”，主语多为人。"),
    ("We still keep in touch by email.", "我们仍通过邮件保持联系。", "常与 with sb 连用表“与…保持联系”。"),
    ("No matter how busy he is, he calls his mom.", "无论多忙，他都会给妈妈打电话。", "后接 wh-词，引导让步状语从句。"),
    ("She broke the cup on purpose to get attention.", "她故意打碎杯子以引起注意。", "多放句末，表“有意而非偶然”。"),
    ("They put off the trip because of the storm.", "因暴风雨他们推迟了旅行。", "及物短语，后接名词/动名词。"),
    ("Women account for half of the workforce.", "女性占劳动力的一半。", "两义：解释原因 / 占比。"),
    ("As a matter of fact, he was the last to leave.", "事实上，他是最后一个离开的。", "书面/口语均可，表“其实”。"),
    ("Thousands of jobs are at stake.", "数以千计的工作岗位面临危险。", "常用 be 动词，表“濒危/成败攸关”。"),
    ("Bear in mind he is still a beginner.", "请记住他还是个初学者。", "后常接 that 从句或名词。"),
    ("The internet brought about huge social change.", "互联网带来了巨大的社会变革。", "宾语多为变化/结果类名词。"),
    ("By and large, customers are satisfied.", "总的来说，顾客是满意的。", "多置句首，表“总体而言”。"),
    ("How do you cope with stress?", "你如何应对压力？", "宾语多为困难/压力，不接人。"),
    ("It took me weeks to get the hang of skiing.", "我花了好几周才掌握滑雪的窍门。", "口语，后接名词/动名词。"),
    ("In spite of his age, he runs fast.", "尽管年事已高，他跑得很快。", "后接名词/动名词，不作连词。"),
    ("In terms of health, walking helps a lot.", "就健康而言，散步很有帮助。", "后接名词，引出评价角度。"),
    ("Wages fail to keep pace with prices.", "工资跟不上物价上涨。", "常与 change/development 等搭配。"),
    ("She can't cook, let alone host a dinner.", "她连做饭都不会，更别提办宴席了。", "用于否定后递进，表“何况”。"),
    ("I lost track of my old classmates.", "我和老同学们失去了联系。", "引申义“与…失联”，不只指时间。"),
    ("He is smart, not to mention hardworking.", "他很聪明，更别提还勤奋了。", "用于补充递进，常用于肯定句。"),
    ("She was fired on the grounds that she lied.", "她被解雇的理由是她说谎。", "正式语体，后接 that 从句。"),
    ("We ran into a problem halfway.", "我们中途遇到了一个问题。", "亦表“遭遇(困难)”，不限于人。"),
    ("He set aside his pride and apologized.", "他放下面子道了歉。", "宾语可为时间/钱/情绪等。"),
    ("Don't take your health for granted.", "不要把健康视为理所当然。", "常用于提醒珍惜易得之物。"),
    ("To some extent, the plan worked.", "在某种程度上，这个计划奏效了。", "多置句首，缓和语气。"),
    ("He acted out his dream for the class.", "他给全班表演了他的梦。", "宾语多为故事/情绪/场景。"),
    ("Add the eggs to the bowl one by one.", "把鸡蛋一个一个加到碗里。", "结构 add A to B，A、B 为名词。"),
    ("The noise added to my headache.", "噪音加重了我的头痛。", "宾语多为负面事物，表“增添”。"),
    ("The bills added up to 500 dollars.", "这些账单加起来有 500 美元。", "主语多为复数，表“总计达”。"),
    ("They agreed on a price at last.", "他们最终就价格达成了一致。", "强调“就某事达成共识”。"),
    ("He agreed to lend me his car.", "他同意把车借给我。", "后接不定式，表答应去做。"),
    ("I apologized to my friend for the mistake.", "我为这个错误向朋友道了歉。", "结构 apologize to sb for sth。"),
    ("She applied for a job at the bank.", "她申请了银行的一份工作。", "宾语多为工作/签证/奖学金。"),
    ("We arrived at the airport two hours early.", "我们提前两小时到达了机场。", "后接较小地点(站/机场/结论)。"),
    ("He asked the waiter for a glass of water.", "他向服务员要了一杯水。", "结构 ask sb for sth。"),
    ("I asked him about his trip.", "我向他询问了他的旅行。", "后接询问的话题/人。"),
    ("My family always backs me up.", "我的家人总是支持我。", "义1支持(人)；义2备份(数据)。"),
    ("The dog barked at the stranger.", "狗对着陌生人叫。", "主语多为狗，at 后接对象。"),
    ("What are you after in the shop?", "你在店里找什么呢？", "口语，表“追捕/寻求”。"),
    ("The land belongs to my uncle.", "这块地属于我叔叔。", "无进行时，主语为物。"),
    ("She bent over to tie her shoelace.", "她弯下腰系鞋带。", "表“俯身”，常接 to do。"),
    ("They bent over backwards to please the guest.", "他们竭尽全力讨好客人。", "含“过分迁就”意味，口语。"),
    ("She broke down in tears at the news.", "听到消息她崩溃得哭了起来。", "义1(机器)抛锚；义2(人)情绪崩溃。"),
    ("War broke out in the region.", "该地区爆发了战争。", "break out 不及物(战争/火)；break into 及物(闯入)。"),
    ("The meeting broke up at noon.", "会议在中午散了。", "义1分手；义2(会议/人群)解散。"),
    ("The medicine brought down his fever.", "药使他退了烧。", "亦表“使降低/击落”。"),
    ("Spring brings in warm weather.", "春天带来了温暖的天气。", "亦表“引入/赚得(收入)”。"),
    ("The damp air brought on his cough.", "潮湿的空气引发了他的咳嗽。", "宾语多为疾病/问题。"),
    ("They brought up three children in the village.", "他们在村里抚养了三个孩子。", "义1养育；义2提出(话题)。"),
    ("Her aunt brought up her younger brother.", "她姑妈抚养了她的弟弟。", "与 bring up 同义，强调“人”作宾。"),
    ("The spaceship burned up in the atmosphere.", "飞船在大气层中烧毁了。", "强调“完全烧尽”。"),
    ("I'll call you tonight.", "我今晚给你打电话。", "最常见义为“打电话给”。"),
    ("This job calls for patience.", "这份工作需要耐心。", "表“需要/要求”，宾语为抽象名词。"),
    ("The game was called off because of fog.", "比赛因大雾取消了。", "及物，宾语为活动/计划。"),
    ("The salesperson called on several clients.", "销售员拜访了几位客户。", "亦表“号召/点名(发言)”。"),
    ("The two effects canceled out in the end.", "两种效应最终相互抵消。", "表“抵消”，常指作用力/影响。"),
    ("He cares about his friends deeply.", "他非常关心他的朋友们。", "强调“在意(感受/福祉)”。"),
    ("Nurses care for the sick day and night.", "护士日夜照顾病人。", "义1照顾；义2(疑问/否定)喜欢。"),
    ("The disease carried off many villagers.", "这场病夺走了许多村民的生命。", "义1带走；义2(病/死)夺去生命。"),
    ("I finally caught up with the latest news.", "我终于赶上了最新消息。", "亦表“补上(进度/消息)”。"),
    ("She changed her old phone for a new one.", "她把旧手机换成了新的。", "结构 change A for B，表“以A换B”。"),
    ("Passengers must check in an hour early.", "乘客须提前一小时值机。", "机场/酒店“办理入住/登机”。"),
    ("Cheer up! Things will get better.", "振作起来！情况会好转的。", "及物/不及物皆可。"),
    ("Volunteers cleaned up the beach.", "志愿者清理了海滩。", "宾语可为房间/环境/ mess。"),
    ("The sky cleared up after the rain.", "雨后天空放晴了。", "义1澄清(误会)；义2(天气)放晴。"),
    ("He climbed out of the pool slowly.", "他慢慢从泳池里爬了出来。", "of 后接容器/水域等。"),
    ("The boy climbed up to the window ledge.", "男孩爬到了窗台上。", "to 后接终点位置。"),
    ("She came across her teacher in the park.", "她在公园偶遇了她的老师。", "偶然遇见，不用于刻意约见。"),
    ("Come along, we are leaving now.", "快来，我们要走了。", "亦用于催促“快跟上/一起来”。"),
    ("Summer will come back next year.", "夏天明年还会回来。", "亦可指“回忆/复原”。"),
    ("He comes from a small town.", "他来自一个小镇。", "表籍贯/来源，无进行时。"),
    ("Come on, you can do it!", "加油，你能行的！", "催促/鼓励/不满，口语感叹。"),
    ("Her new book came out last month.", "她的新书上个月出版了。", "亦表“出版/结果是”。"),
    ("Why don't you come over to our place?", "你何不过来我们家？", "指“从别处来到(某地)”。"),
    ("His dream of flying came true.", "他飞行的梦想成真了。", "主语为 dream/wish 等。"),
    ("A new problem came up at work.", "工作上出现了一个新问题。", "亦表“发生/被提及”。"),
    ("They came up with a clever idea.", "他们想出了一个聪明的点子。", "宾语多为想法/计划/答案。"),
    ("He communicates with his son by video call.", "他通过视频通话和儿子交流。", "with 后接交流对象。"),
    ("Compared with last year, sales rose.", "与去年相比，销量上升了。", "表“与…比较”，常置于句首。"),
    ("She complained about the slow service.", "她抱怨服务太慢。", "complain 为动词，about 后接对象。"),
    ("He copied down the address carefully.", "他仔细抄下了地址。", "宾语多为文字/数字/笔记。"),
    ("She covered the table with a cloth.", "她用一块布盖住了桌子。", "结构 cover A with B。"),
    ("You should cut down on sugar.", "你应该减少糖的摄入。", "义1砍倒(树)；义2 cut down on 减少。"),
    ("Our call was cut off suddenly.", "我们的通话突然被切断了。", "亦表“中断(联系/供应)”。"),
    ("Cut out the bad part of the apple.", "把苹果坏掉的部分切掉。", "亦表“剪下/割掉”。"),
    ("He cut up the meat into small pieces.", "他把肉切成小块。", "宾语多为食物，表“切碎”。"),
    ("The castle dates from the Middle Ages.", "这座城堡始建于中世纪。", "无进行时，后接时间点。"),
    ("How do you deal with rude people?", "你如何应付无礼的人？", "宾语可为问题/人/话题。"),
    ("We decided on the blue one at last.", "我们最终选了蓝色的那个。", "on 后接选定的人/物/方案。"),
    ("It depends on the weather.", "这取决于天气。", "亦表“取决于”，后接条件。"),
    ("Children depend on their parents.", "孩子们依靠父母。", "on 后接被依靠的人。"),
    ("The old man died of old age.", "那位老人寿终正寝。", "die of 内因(病/老)；die from 外因(伤/事故)。"),
    ("Many dialects are dying out.", "许多方言正在消亡。", "多指物种/习俗“逐渐消失”。"),
    ("We dug up the old tree stump.", "我们挖出了那棵老树桩。", "宾语多为埋藏之物。"),
    ("She dipped the pen into the ink.", "她把笔蘸进墨水。", "结构 dip A into B。"),
    ("The car disappeared into the tunnel.", "汽车消失在隧道里。", "into 后接消失的去处。"),
    ("She did well in the interview.", "她面试表现很好。", "in 后接学科/活动/考试。"),
    ("He dreamed about his childhood home.", "他梦到了童年的家。", "about 后接梦中情景。"),
    ("She dreams of a better life.", "她梦想着更好的生活。", "亦表“梦想(做某事)”，后接名词/动名词。"),
    ("Water dripped onto the floor.", "水滴到了地板上。", "onto 后接被滴落的物面。"),
    ("His endless questions drive me mad.", "他没完没了的问题快把我逼疯了。", "口语夸张，表“使…受不了”。"),
    ("We dropped in at a cafe nearby.", "我们顺道去了附近一家咖啡馆。", "drop in at 接地点；drop in on 接人。"),
    ("She dropped her keys on the way.", "她把钥匙掉在了路上。", "及物，宾语为掉落物。"),
    ("The well dried up in the drought.", "井在干旱中干涸了。", "亦表“(资金/话题)枯竭”。"),
    ("The kids ate up the cookies.", "孩子们把饼干吃光了。", "eat up 吃光；use up 用尽。"),
    ("The movie ends with a happy scene.", "电影以幸福的场景收尾。", "with 后接结束的内容。"),
    ("The baby fell asleep in my arms.", "宝宝在我怀里睡着了。", "常作系表，表“入睡”。"),
    ("Don't fall behind with your rent.", "别拖欠房租。", "常与 in/with 连用。"),
    ("The child fell off the bike.", "孩子从自行车上摔了下来。", "fall off 从…掉下；fall down 倒下/跌倒。"),
    ("He felt ashamed of his lie.", "他为自己的谎言感到羞愧。", "of 后接感到羞愧的事。"),
    ("Do you feel like a cup of tea?", "你想来杯茶吗？", "义1想做(接动名词)；义2像(接名词)。"),
    ("He feels like taking a walk.", "他想去散散步。", "后接动名词，表“想要”。"),
    ("We feel proud of our team.", "我们为自己的团队感到骄傲。", "of 后接引以为傲的人/事。"),
    ("I feel sorry about the delay.", "我对这次延误感到抱歉。", "about 后接遗憾的事。"),
    ("She feels sorry about hurting his feelings.", "她为伤害他的感情感到内疚。", "about 后接动名词。"),
    ("She felt unhappy about the result.", "她对结果感到不开心。", "about 后接令人不快的事。"),
    ("After rest, he began to feel well.", "休息后，他感觉好些了。", "well 此处指“身体好”。"),
    ("We must fight against corruption.", "我们必须与腐败作斗争。", "against 后接对抗的对象。"),
    ("They fought for equal rights.", "他们为平等权利而战。", "against 反对；for 拥护/争取。"),
    ("He filled the glass with juice.", "他把杯子倒满了果汁。", "结构 fill A with B。"),
    ("The room filled with laughter.", "房间里充满了笑声。", "亦可用被动 be filled with。"),
    ("I found out he was lying.", "我发现他在撒谎。", "强调“查明/获知真相”。"),
    ("The angry dog flew at the thief.", "那只愤怒的狗扑向了小偷。", "表“猛扑向”，at 后接目标。"),
    ("He focused on learning the guitar.", "他专注于学吉他。", "on 后接名词/动名词。"),
    ("They forced him to sign the paper.", "他们强迫他在文件上签了字。", "结构 force sb to do。"),
    ("She gets along well with her neighbors.", "她和邻居相处得很融洽。", "比 get along with 更强调“融洽”。"),
    ("Get on the bus quickly.", "快上车。", "get on 上(车/马)；get off 下；get back 取回。"),
    ("We got close to the finish line.", "我们接近了终点线。", "to 后接接近的目标。"),
    ("Get down from the ladder carefully.", "小心从梯子上下来。", "亦表“下来/使沮丧”。"),
    ("Let's get down to planning the trip.", "我们来着手规划这次旅行吧。", "to 后接名词/动名词，非不定式。"),
    ("My cousin got married last year.", "我表哥去年结婚了。", "表示“结婚”动作，非状态。"),
    ("How are you getting on with your project?", "你的项目进展得怎么样？", "义1相处；义2(工作)进展。"),
    ("She got over her fear of heights.", "她克服了对高度的恐惧。", "亦表“从(疾病/打击)恢复”。"),
    ("The kids got ready for school.", "孩子们为学校做好了准备。", "for 后接准备的对象。"),
    ("I can't get through to him by phone.", "我打电话联系不上他。", "亦表“接通(电话)/熬过”。"),
    ("We got to the station just in time.", "我们刚好准时到达车站。", "后接地点，表“抵达”。"),
    ("The pill helped him get to sleep.", "药片帮他入睡了。", "强调“进入睡眠”的过程。"),
    ("She got worried when he was late.", "他迟到时她担心起来。", "系表结构，表“变得担心”。"),
    ("He gave away all his old books.", "他把所有旧书都送人了。", "义1赠送；义2泄露(秘密)。"),
    ("He gave up smoking last year.", "他去年戒烟了。", "up 后接放弃的事物。"),
    ("Don't give up, keep trying.", "别放弃，继续尝试。", "可及物/不及物。"),
    ("I gave the phone back to its owner.", "我把手机还给了主人。", "结构 give sth back (to sb)。"),
    ("It goes against my beliefs.", "这违背了我的信念。", "亦表“不利于(某人)”。"),
    ("The plan went ahead as scheduled.", "计划按预定进行。", "亦表“开始吧/继续(许可)”。"),
    ("The pain will go away soon.", "疼痛很快就会消失。", "亦表“(病痛)消退”。"),
    ("The sun went down behind the hills.", "太阳落到了山后。", "亦表“日落/下跌”。"),
    ("He went down the stairs two at a time.", "他一步两级地走下楼。", "指“下楼梯”这一动作。"),
    ("The dog went inside the house.", "狗走进了屋里。", "与 go outside 相对。"),
    ("His wallet went missing on the bus.", "他的钱包在公交车上不见了。", "系表，表“丢失/失踪”。"),
    ("She went off to Guangzhou for a holiday.", "她去广州度假了。", "go off to + 地名，表“前往”。"),
    ("What's going on outside?", "外面发生什么事了？", "义1继续；义2发生(进行式)。"),
    ("She went on talking after the break.", "休息后她继续讲了下去。", "指“不间断地继续同一动作”。"),
    ("They went on working till midnight.", "他们继续工作到午夜。", "同 go on doing，后接动名词。"),
    ("The fire has gone out.", "火已经灭了。", "亦表“(火/灯)熄灭”。"),
    ("This software is going out of date.", "这个软件逐渐过时了。", "系表，表“过时/旧式”。"),
    ("The children went outside to play.", "孩子们到外面去玩了。", "与 go inside 相对。"),
    ("Go straight ahead and you'll see the gate.", "一直往前走，你就会看到大门。", "指路用语，表“直行”。"),
    ("He went straight to bed after dinner.", "他饭后直接去睡了。", "to 后接目的地。"),
    ("The child went to bed without a fuss.", "孩子乖乖上床睡觉了。", "指“去睡”动作，非 asleep。"),
    ("The baby went to sleep in minutes.", "宝宝几分钟就睡着了。", "强调“进入睡眠”状态。"),
    ("The temperature went up sharply.", "气温急剧上升。", "亦表“上升/升起”。"),
    ("Would you like to go with me?", "你愿意和我一起去吗？", "亦表“选择/搭配”。"),
    ("He grew up in a small village.", "他在一个小村庄长大。", "指“长大/成长”，不及物。"),
    ("Guard against catching a cold.", "要提防感冒。", "against 后接防范的事。"),
    ("He handed in his resignation.", "他递交了辞呈。", "宾语多为作业/报告/申请。"),
    ("Please hand in your form by Monday.", "请在周一前交上你的表格。", "hand in 上交；hand out 分发。"),
    ("What happened to your hand?", "你的手怎么了？", "常用于 What happened to...?"),
    ("A strange thing happened to her.", "一件奇怪的事发生在她身上。", "to 后接经历者。"),
    ("An accident happened to the bridge.", "那座桥发生了事故。", "同 happen to，to 后接对象。"),
    ("Did you hear about the new cafe?", "你听说那家新咖啡馆了吗？", "指“听人说起(某消息)”。"),
    ("Hope to hear from you soon.", "希望很快收到你的信。", "from 后接寄信/联系的人。"),
    ("We heard from him yesterday.", "我们昨天收到了他的消息。", "同 hear from，强调“某人”。"),
    ("I never heard of such a rule.", "我从未听说过这样的规定。", "指“知道有(某人/某事)”。"),
    ("Can you help him with his homework?", "你能帮帮他做作业吗？", "help sb with sth 表“在某方面帮某人”。"),
    ("She helped her dad with the dishes.", "她帮爸爸洗了碗。", "with 后接具体事务。"),
    ("Hold on, I'm putting you through.", "稍等，我给您转接。", "电话中“别挂”；亦可表“坚持”。"),
    ("He held up the trophy proudly.", "他骄傲地举起了奖杯。", "亦表“延误/支撑”。"),
    ("He hurried to the door when the bell rang.", "门铃响时他匆匆走向门口。", "to 后接匆忙前往之地。"),
    ("Hurry up, the meeting starts at nine.", "快点，会议九点开始。", "催促用语，表“快些”。"),
    ("Leave immediately!", "立刻离开！", "并列两词：immediately 立刻；keep in touch with 保持联系。"),
    ("May I join in the game?", "我可以加入这个游戏吗？", "后接活动，表“参与”。"),
    ("He jumped out of bed at once.", "他立刻从床上跳了起来。", "of 后接跳出的处所。"),
    ("The dam keeps back the floodwater.", "大坝挡住了洪水。", "亦表“隐瞒/忍住(眼泪)”。"),
    ("It kept raining all afternoon.", "雨下了整整一个下午。", "后接动名词，表“持续做”。"),
    ("He kept on laughing at the joke.", "他听了笑话一直笑。", "强调“反复/坚持地继续”。"),
    ("Keep still while I take the photo.", "我拍照时别动。", "表“保持不动”，多用于指令。"),
    ("Keep the desk tidy after use.", "用完后保持桌面整洁。", "后接名词+形容词。"),
    ("Keep up the pace, don't slow down.", "保持这个节奏，别慢下来。", "亦表“跟上/保持(水平)”。"),
    ("I can't keep up with his speed.", "我跟不上他的速度。", "with 后接被追赶的对象。"),
    ("Keep the dog off the sofa.", "别让狗上沙发。", "结构 keep A off B。"),
    ("He knocked into me in the dark.", "黑暗中他撞到了我。", "into 后接被撞到的人。"),
    ("Someone is knocking on the window.", "有人在敲窗户。", "on 后接被敲的表面。"),
    ("He knocked the nail out of the wall.", "他把钉子从墙上敲了出来。", "结构 knock A out of B。"),
    ("The bus knocked the man down.", "公交车把那个男人撞倒了。", "亦指“车撞倒人”。"),
    ("The wave knocked him off the rock.", "浪把他从岩石上冲了下来。", "off 后接脱离的位置。"),
    ("The blow knocked him out cold.", "那一击把他打昏了。", "亦表“(拳击)击倒获胜”。"),
    ("What do you know about this city?", "你对这座城市了解多少？", "指“知道…的情况”。"),
]

src = json.load(open('phr_batch_todo.json'))
assert len(src) == 200, f"input has {len(src)} entries"
assert len(enrich) == 200, f"enrich has {len(enrich)} entries"

out = {}
missing = []
for i, d in enumerate(src):
    p = d['p']
    en2, cn2, note = enrich[i]
    # sanity: en2 must contain the phrase (allow combined keys -> check any slash-part)
    parts = [x.strip() for x in p.split('/')]
    # for combined keys, at least one part should appear in en2 (normalized)
    en2_low = en2.lower()
    ok = any(part.lower() in en2_low for part in parts if part)
    if not ok:
        missing.append((i, p, en2))
    out[p] = {"en2": en2, "cn2": cn2, "note": note}

if missing:
    print("WARNING phrases not literally found in en2:")
    for m in missing:
        print(m)

# also verify no duplicate keys dropped anything
assert len(out) == 200, f"output keys {len(out)} != 200 (duplicate p?)"

with open('phr_enriched.json', 'w', encoding='utf-8') as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print("WROTE", len(out), "keys to phr_enriched.json")
